name: treeed_flutter
description: "Treeed state manager for Flutter."
version: 0.1.1
homepage: https://github.com/marat0n/treeed_flutter

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  treeed: ^0.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - treeed
  - flutter-state
  - state-manager
  - minimalistic
